[patch.crates-io]
# this needs to be at parity with MODULE.bazel
audio_streams = { git = "https://chromium.googlesource.com/crosvm/crosvm", rev = "ca4ee802a94ea2861fa03872fa263fcea744d83d" }
libcras = { git = "https://chromium.googlesource.com/crosvm/crosvm", rev = "ca4ee802a94ea2861fa03872fa263fcea744d83d" }
# this needs to be at parity with the crosvm submodule third_party/minijail
minijail = { git = "https://chromium.googlesource.com/chromiumos/platform/minijail", rev = "bfd22f25fd2302fe4ae5121d80c836e0f124e742" }
